version: '3'

services:
  interflow-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "interflow-backend"
    ports:
      - "5000:5000"
    container_name: "interflow-backend"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=5000
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
